services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - interview-reminder

volumes:
  postgres_data:

networks:
  interview-reminder: